server:
  servlet:
    context-path: /api/v1/messages
  port: 8084

spring:
  application:
    name: messages-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  amqp:
    queue: queue
    routing_key: routing_key
    exchange: topic
    port: 15672
    host: localhost
    login: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/snetwork_messages
    username: username
    password: password
