server:
  servlet:
    context-path: /api/v1/conversation
  port: 8083

spring:
  application:
    name: conversations-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/snetwork_conversations
    username: username
    password: password