server:
  port: 9000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: username
          password: password
          uri: https://example.com/config-repo
          default-label: some-label
